version: '3.3'
services:

    php:
        container_name: "ad-php-${DOCKER_BUILD_TAG}"
        image: "ad-php:${DOCKER_BUILD_TAG}"
        build:
            context:    ./
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - ./var/log/:/var/www/html/var/log:delegated
        depends_on:
            - nginx
            - mysql
        command: php-fpm
        networks:
            ad_network:


    nginx:
        container_name: "ad-nginx-${DOCKER_BUILD_TAG}"
        image: "ad-nginx:${DOCKER_BUILD_TAG}"
        build:
            context:    ./
            dockerfile: ./.docker/nginx/Dockerfile
        volumes:
            - ./.docker/nginx/server-dev.conf:/etc/nginx/conf.d/server.conf:cached
        ports:
            - '80:8080'
        command: sh /var/run/wait-for.sh php:9000 -t 20 -- nginx
        networks:
            ad_network:

    mysql:
        image: mysql:8
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'mysql_user'
            MYSQL_PASSWORD: 'mysql_pass'
            MYSQL_ROOT_PASSWORD: 'root_pass'
        ports:
            - '3306:3306'
        volumes:
            - mysql-db:/var/lib/mysql
        networks:
            ad_network:

volumes:
    mysql-db:

networks:
    ad_network:
        driver: bridge
        ipam:
            config:
                -   subnet: 10.10.0.0/16
